[project]
name = "machine-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dask>=2025.5.1",
    "ipykernel>=6.29.5",
    "matplotlib",
    "pandas>=2.3.1",
    "scikit-learn",
    "tensorflow>=2.19.0",
]
